[#2] 검색화면 구현
thinkingPotatoes/FRONTEND pull request #20
Opened 2023-08-03 00:39 UTC by kimssumin

### 이슈번호
#2 

### 개요(간단한 작업 내용 설명)

검색화면 전체적인 레이아웃과, 검색 바 입력, 자동완성 , 그리고 검색 결과 화면을 구현하였습니다
최근 검색어 부분도 localStorage 를 활용하여 최대 10개까지 관리되도록 구현하였습니다.
최근검색어 부분과, 추천 검색어 부분의 검색어 chip 들은 swiper 를 통해 슬라이더로 구현하였습니다.

### 스크린 샷 및 화면(뷰 개발시 필수)

**검색화면**
![image](https://github.com/thinkingPotatoes/FRONTEND/assets/96935132/424b6150-ecfd-472d-90b5-0f936b655a43)

**검색어 입력 화면**
![image](https://github.com/thinkingPotatoes/FRONTEND/assets/96935132/3598647a-f80f-4af6-b1a7-d2df929b0ead)
![image](https://github.com/thinkingPotatoes/FRONTEND/assets/96935132/a0c97e4e-1f43-41f1-9c0b-65ae5b6c723b)

**검색 결과 화면**
![image](https://github.com/thinkingPotatoes/FRONTEND/assets/96935132/54973afd-cdd6-4040-8f73-9529c094b0e7)
 

### 작업한 내용

검색 바 구현 [685292e]
최근 검색어 구현 [66a4442] [43cb08a] [50591ac]
인기 검색어 구현 [525d386] 
검색 결과화면 구현 [728a07f]

2023-08-06 06:56 UTC, jee-woo requested changes
수고하셨습니다!

2023-08-06 06:56 UTC, jee-woo commented on src/components/Search/HotSearch.tsx
> +export default HotSearch;
이 파일 외에 대부분 파일에서는 styled-components 코드 전에 export 문을 쓰셨는데, 저는 다 이렇게 마지막에 export 문을 작성했거든요! export 문 위치를 통일하는게 어떨까요?

2023-08-06 06:56 UTC, jee-woo commented on src/components/Search/AutoSearchList.tsx
> +  const handleSearchItemClick = (city: string) => {
컴포넌트 안의 함수를 다른 파일에서는 function 선언식을 사용하셨는데 여기서는 화살표 함수를 사용하신 이유가 있을까요? 저는 컴포넌트 외의 함수는 화살표 함수로 사용했어서요!

2023-08-06 06:56 UTC, jee-woo commented on src/components/Search/ResultSearch.tsx
> +`;
여기서부터 선언된 스타일 컴포넌트들에 개행이 필요할 것 같아요!

2023-08-06 06:57 UTC, jee-woo approved these changes

2023-08-08 07:42 UTC, kimssumin commented on src/components/Search/ResultSearch.tsx
> +`;
넵 수정했습니다 감사합니다 :)

2023-08-08 07:43 UTC, kimssumin commented on src/components/Search/AutoSearchList.tsx
> +  const handleSearchItemClick = (city: string) => {
우선 저번 회의때 모든 함수를 function 함수로 통일한다고 이해를 해서 function 함수로 전부 작성을 하다가,
제가 화살표함수가 조금 더 손에 익어서 저도 모르게 고치지 못한 부분이 있었던 것 같아요!

지금은 일단 function 으로 다 통일하여 수정해두었는데, 컴포넌트 외의 함수를 화살표함수로 사용하는 것을 허용할지 다음회의때 정해보면 좋을 것 같습니다

감사합니다 :)

2023-08-08 07:44 UTC, kimssumin commented on src/components/Search/HotSearch.tsx
> +export default HotSearch;
넵 ! 수정해두었습니다

2023-08-18 12:48 UTC, GunBros commented on src/components/Search/RecentSearch.tsx
> +  const [recentSearch, setRecentSearch] = useState<string[]>(defaultMovieList);
1. recentSearch를 로컬스토리지에서 가져오니 defaultMovieList로 초기화를 하지 않아도 될 것 같네요.
2. (질문) 밑에 useEffect를 통해서 로컬 스토리지에 최근 검색어가 있으면 세팅을 해주는데 useState에 바로 세팅하는 방법은 동작하지 않을까요?

2023-08-18 12:48 UTC, GunBros commented on src/components/Search/SearchBox.tsx
> +  useEffect(() => {
(질문) 로컬 스토리지에서 최근 검색어를 가져오는 로직이 RecentSearch에서도 같이 사용되는 부분 같은데 커스텀 훅이나 함수로 분리할 수는 없을까요?

2023-08-18 12:50 UTC, GunBros commented on src/components/Search/AutoSearchList.tsx
> +  const handleSearchItemClick = (city: string) => {
음 확실히 애매하긴 하네요. 저도 컴포넌트 안에서 사용되는 핸들러 함수나 이벤트 함수들은 화살표 함수로 사용하고 컴포넌트는 함수 선언식을 사용하긴 하는데 딱히 이유 없이 그렇게 쓰고 있기는 해서.. 다음 회의때 논의해보면 좋을 것 같습니다.

2023-08-21 01:28 UTC, kimssumin commented on src/components/Search/RecentSearch.tsx
> +  const [recentSearch, setRecentSearch] = useState<string[]>(defaultMovieList);
넵, local storage 로 세팅하면서 defaultMovieList 를 바꿨어야했던 부분을 제가 놓치고있었어요!
감사합니다 :) 수정해두었어요 !

2023-08-21 01:29 UTC, kimssumin commented on src/components/Search/SearchBox.tsx
> +  useEffect(() => {
이 부분도 말씀해주신대로 hook으로 분리해두는게 좋은거같아 useLocalStorage hook 만들어두었습니다!
감사합니다

2023-08-21 02:17 UTC, GunBros commented on src/components/Search/RecentSearch.tsx
> +    console.log(JSON.stringify(recentSearch));
console.log 삭제해주세용

2023-08-21 02:17 UTC, GunBros commented on src/components/Search/SearchInputBar.tsx
> +    //향수 이름 검색에 ENTER 지원
싸피의 영향이 여기까지...

2023-08-21 02:17 UTC, GunBros commented on src/components/Search/RecentSearch.tsx
> +    console.log('search', search);
console.log!

2023-08-22 00:29 UTC, kimssumin commented on src/components/Search/RecentSearch.tsx
> +    console.log('search', search);
아앗...! console 전부 제거했습니다..! 😂

2023-08-22 01:06 UTC, GunBros approved these changes
:+1: 고생하셨습니다!

2023-08-22 01:06 UTC, merged